[assets.prod]
name = "Flipbook"
description = "Flipbook is a storybook plugin that previews UI components in a sandboxed environment. With it you can isolate distinct parts of your game's UI to hammer out edge cases and complex states without having to run through the whole UI."
model = "build/Flipbook.rbxm"
environment = "prod"
type = "Plugin"

[assets.dev]
name = "Flipbook (Dev)"
description = """This is a development version of Flipbook for testing out unreleased changes.

View the latest release of Flipbook here: https://create.roblox.com/store/asset/8517129161/flipbook"""
model = "build/Flipbook.rbxm"
environment = "prod"
type = "Plugin"

[environments.prod]
creatorId = 1343930
creatorType = "User"
universeId = 6599100156
placeId = 84837374448022
