[inputs."img/ChevronRight.png"]
hash = "4c91853652b4e0a6317804c54db6397ac0c710c819b282f7be2179e3abdc879c"
id = 130695877008766
slice = [[49, 226], [81, 258]]
packable = true

[inputs."img/Component.png"]
hash = "d51b19d5f35ac87fd8156500828f3e217b6fc420b70fee5d97b3577e4e6a8843"
id = 130695877008766
slice = [[0, 275], [32, 307]]
packable = true

[inputs."img/FlipbookIcon.png"]
hash = "423e3dcff54fce8824f14d7cadcfb90eef2abecd817df2bee13951bd2674f79a"
id = 130695877008766
slice = [[231, 0], [295, 64]]
packable = true

[inputs."img/Folder.png"]
hash = "4c0e80a363d36a4d127d410795cb13eec74d55871b70174636c0c962c242835c"
id = 130695877008766
slice = [[345, 0], [377, 32]]
packable = true

[inputs."img/GitHubMark.png"]
hash = "a0fb973cd9bf0c1123dbe783f7a4093dbcf9b4910d6e385c16a837a04a02306c"
id = 130695877008766
slice = [[0, 0], [230, 225]]
packable = true

[inputs."img/Search.png"]
hash = "0ab89c0309f577f3ccae0e03b45292f6e2bca51cc9b8250f56ad756e04231c57"
id = 130695877008766
slice = [[296, 49], [328, 81]]
packable = true

[inputs."img/Storybook.png"]
hash = "2a4b8bd513a8fa7eebae482943ab3435a659359bd94b24eff1c3dcc6f1244799"
id = 130695877008766
slice = [[231, 108], [263, 140]]
packable = true
