[package]
name = "flipbook-labs/flipbook"
version = "1.5.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
Roact = "roblox/roact@1.4.4"
React = "jsdotlua/react@17.0.1"
ReactRoblox = "jsdotlua/react-roblox@17.0.1"
Sift = "csqrl/sift@0.0.4"
t = "osyrisrblx/t@3.0.0"
ModuleLoader = "flipbook-labs/module-loader@0.6.1"
TestEZ = "roblox/testez@0.4.1"
RoactSpring = "chriscerie/react-spring@1.1.3"
