[package]
name = "flipbook-labs/flipbook"
version = "1.5.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
CSF = "flipbook-labs/csf@0.1.0"
ModuleLoader = "flipbook-labs/module-loader@0.6.1"
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
ReactSpring = "chriscerie/react-spring@2.0.0"
Sift = "csqrl/sift@0.0.4"
t = "osyrisrblx/t@3.0.0"

# dev dependencies
Roact = "roblox/roact@1.4.4"
TestEZ = "roblox/testez@0.4.1"
Fusion = "elttob/fusion@0.2.0"
