[package]
name = "vocksel/roact-storybook"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
Roact = "roblox/roact@1.4.2"
RoactHooks = "kampfkarren/roact-hooks@0.3.0"
Flipper = "reselim/flipper@2.0.0"
Llama = "freddylist/llama@1.1.1"
t = "osyrisrblx/t@3.0.0"
ModuleLoader = "vocksel/module-loader@0.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"