[package]
name = "flipbook-labs/flipbook"
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
ModuleLoader = "flipbook-labs/module-loader@0.6.2"
Storyteller = "flipbook-labs/storyteller@0.6.0"
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
ReactSpring = "chriscerie/react-spring@2.0.0"
Sift = "csqrl/sift@0.0.8"
t = "osyrisrblx/t@3.0.0"

# dev dependencies
Roact = "roblox/roact@1.4.4"
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
