[package]
name = "vocksel/flipbook"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
Roact = "roblox/roact@1.4.4"
React = "core-packages/roact-compat@17.0.1-rc.16"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"
Sift = "csqrl/sift@0.0.4"
t = "osyrisrblx/t@3.0.0"
ModuleLoader = "vocksel/module-loader@0.5.0"
TestEZ = "roblox/testez@0.4.1"
RoactSpring = "chriscerie/react-spring@1.1.2"
