name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        channel: [dev, prod]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Create .env
        run: cp .env.template .env

      - name: Get model file name
        run: |
          name=$(jq -r .name default.project.json)
          sha=${GITHUB_SHA:0:7}
          echo "MODEL_FILE=$name-$sha.rbxm" >> $GITHUB_ENV

      - name: Build
        run: lute scripts/build.luau plugin --channel ${{ matrix.channel }} --output ${{ env.MODEL_FILE }}

      - uses: actions/upload-artifact@v4
        with:
          name: flipbook-plugin-${{ matrix.channel }}
          path: ${{ env.MODEL_FILE }}

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ env.MODEL_FILE }}

  build-package:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        package: [flipbook-core]
        target: [rotriever]
        channel: [dev, prod]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Create .env
        run: cp .env.template .env

      - name: Build
        run: lute scripts/build.luau workspace --channel ${{ matrix.channel }} --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v6
        with:
          path: build/${{ matrix.package }}-${{ matrix.target }}
          name: ${{ matrix.package }}-${{ matrix.target }}-${{ matrix.channel }}

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            build/${{ matrix.package }}-${{ matrix.target }}/src/workspace
            build/${{ matrix.package }}-${{ matrix.target }}/src/init.lua
            build/${{ matrix.package }}-${{ matrix.target }}/default.project.json
            build/${{ matrix.package }}-${{ matrix.target }}/rotriever.toml

  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Setup Lune typedefs
        run: lune setup

      - name: Setup Lute typedefs
        run: lute setup

      - name: Lint
        run: lute scripts/lint.luau

      - name: Run Luau analysis
        run: lute scripts/analyze.luau

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Create .env
        run: cp .env.template .env

      - name: Run tests
        run: lute scripts/test.luau
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
